name: SoulCraftX
version: '${project.version}'
main: net.tnn1nja.soulCraftX.Main
authors: [ tnn1nja, bomotod ]
api-version: '1.21'
commands:
  jump:
    description: Reimplements jumping the way Mojang was too scared to.
    usage: /<command>
    aliases: [ j, joomp ]